### ISSUE TITLE
[Feedback]: example is broken

### ISSUE THREAD

**Issue by leftsock** [canonical/ubuntu-server-documentation#207]
### Page URL

https://documentation.ubuntu.com/server/explanation/networking/configuring-networks/

### Select an option

- [ ] I found what I was looking for
- [ ] I couldn't find what I was looking for
- [x] I found the information, but it was incorrect
- [ ] I found the information, but it was incomplete
- [ ] I found the information, but it was confusing
- [ ] I encountered a technical issue (e.g., broken link, image not loading)

### Issue Description

```
cat >/etc/netplan/50-couch5.yaml <<'__EOF__'
network:
  version: 2
  ethernets:
    enX0:
      dhcp4: false
    addresses:
      - 192.168.0.5/24
    routes:
      - to: default
        via: 192.168.0.1
    nameservers:
      addresses: [192.168.0.1]
__EOF__
chmod og= /etc/netplan/50-couch5.yaml
netplan apply

```

Looks like the example, but on ubuntu24, I get the error:

```
/etc/netplan/50-couch5.yaml:7:7: Error in network definition: expected mapping (check indentation)
      - 192.168.0.5/24
      ^

```
